export const LOGIN = "http://localhost:8800/api/auth/login"
export const GET_USER = "http://localhost:8800/api/auth/getuser"
export const REGISTER = "http://localhost:8800/api/auth/register"
export const ALL_USERS = "http://localhost:8800/api/auth/all"
export const ADD_MESSAGE = "http://localhost:8800/api/messages/add-message"
export const ALL_MESSAGES = "http://localhost:8800/api/messages/all-messages"